
version: '3'

# This file defines development setting, e.g. debugging & realoading

services:
  web:
    build: ./
    image: species-challenge:latest
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8081:8081"
    environment:
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=TRUE # Stuff printed to logs are visible immediately
    entrypoint: >
      gunicorn 
      --chdir /usr/src/app main:app -w 1 
      --threads 1 -b 0.0.0.0:8081
      --timeout 120 
      --reload
#      --reload-extra-file /usr/src/app/templates/base.html
    # Note that the extra-files have to exist, otherwise dockec-compose will complain "Error: File ... does not exists."  
    depends_on:
      - db

  db:
    image: mariadb:10.5
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      - db
      
volumes:
  mariadb_data: