kind: Template
apiVersion: template.openshift.io/v1
parameters:
  - name: BRANCH
    required: true
  - name: APP
    required: true
    value: species-challenge
  - name: APP_PORT
    required: true
    value: "8081"
  - name: DB
    required: true
    value: mariadb
  - name: DB_IMAGE
    required: true
    value: quay.io/centos7/mariadb-105-centos7
  - name: DB_PORT
    required: true
    value: "3306"
  - name: MYSQL_DATABASE
    required: true
  - name: MYSQL_USER
    required: true
  - name: MYSQL_PASSWORD
    required: true
  - name: FINBIF_API_TOKEN
    required: true
  - name: FLASK_SECRET_KEY
    required: true
  - name: HOST
    required: true
  - name: GITHUB_SECRET
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{64}"
metadata:
  name: ${APP}
objects:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
   name: ${DB}-${BRANCH}
  spec:
    storageClassName: "standard-rwo"
    accessModes:
    - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    resources:
      requests:
        storage: "20Gi"
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP}-${BRANCH}:latest
    source:
      type: Git
      git:
        uri: https://github.com/luomus/${APP}.git
        ref: ${BRANCH}
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.rahti
      type: Docker
    triggers:
    - type: ConfigChange
    - type: GitHub
      github:
        secret: ${GITHUB_SECRET}
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}-${BRANCH}
      spec:
        containers:
        - image: ${APP}-${BRANCH}:latest
          name: ${APP}-${BRANCH}
          env:
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
          - name: MYSQL_HOST
            value: ${DB}-${BRANCH}
          - name: FINBIF_API_TOKEN
            value: ${FINBIF_API_TOKEN}
          - name: FLASK_SECRET_KEY
            value: ${FLASK_SECRET_KEY}
          ports:
          - containerPort: ${{APP_PORT}}
#          livenessProbe:
#            httpGet:
#              path: ?????????????????????????????????????????????????????????
#              port: ${{APP_PORT}}
#            failureThreshold: 5
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              path: ?????????????????????????????????????????????????????????
#              port: ${{APP_PORT}}
#            initialDelaySeconds: 5
#            periodSeconds: 5
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${APP}-${BRANCH}
        from:
          kind: ImageStreamTag
          name: ${APP}-${BRANCH}:latest   
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${DB}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    replicas: 1
    selector:
      app: ${APP}
      deploymentconfig: ${DB}-${BRANCH}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${DB}-${BRANCH}
      spec:
        containers:
        - image: ${DB_IMAGE}
          name: ${DB}-${BRANCH}
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: ${DB}-${BRANCH}
          ports:
            - containerPort: ${{DB_PORT}}
#          livenessProbe:
#            exec:
#              command: ????????????????????????????????????????????????????
#            failureThreshold: 5
#            periodSeconds: 30
#          readinessProbe:
#            httpGet:
#              command: ????????????????????????????????????????????????????
#            initialDelaySeconds: 5
#            periodSeconds: 5
          env:
          - name: MYSQL_DATABASE
            value: ${MYSQL_DATABASE}
          - name: MYSQL_USER
            value: ${MYSQL_USER}
          - name: MYSQL_PASSWORD
            value: ${MYSQL_PASSWORD}
        volumes:
        - name: ${DB}-${BRANCH}
          persistentVolumeClaim:
            claimName: ${DB}-${BRANCH}
    triggers:
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${APP_PORT}
      port: ${{APP_PORT}}
      targetPort: ${{APP_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${BRANCH}
- kind: Service
  apiVersion: v1
  metadata:
    name: ${DB}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    ports:
    - name: ${DB_PORT}
      port: ${{DB_PORT}}
      targetPort: ${{DB_PORT}}
    selector:
      app: ${APP}
      deploymentconfig: ${DB}-${BRANCH}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${APP}-${BRANCH}
    labels:
      app: ${APP}
  spec:
    host: ${HOST}
    port:
      targetPort: ${{APP_PORT}}
    tls:
      termination: edge
    to:
      kind: Service
      name: ${APP}-${BRANCH}
    wildcardPolicy: None

